"""add model Brand

Revision ID: 42e0ef2f3059
Revises: 5c0583e7d1b8
Create Date: 2026-09-08 22:39:33.125079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e0ef2f3059'
down_revision: Union[str, Sequence[str], None] = '5c0583e7d1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key('fk_product_brand_id', 'products', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_product_category_id', 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_product_category_id', 'products', type_='foreignkey')
    op.drop_constraint('fk_product_brand_id', 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'brand_id')
    op.drop_table('brands')
    # ### end Alembic commands ###
